### ISSUE TITLE
"I" Block Rotation Issue

### ISSUE THREAD

**Issue by hamidnazari** [ARMoir/Tetris#1]
I haven't figured out how to reliably reproduce this, but sometimes the `I` blocks turn diagonal after rotation. I suspect if the block is moved left or right, then this can happen. Otherwise it seems once the block spawns, rotating it alone won't trigger this.

Here's an example:

```
                        <! . . . . . . . . . .!>
                        <! . . . . . .[] . . .!>
                        <! . . . . . . . . . .!>
                        <! . . . . .[] . . . .!>
                        <! . . . . . . . . . .!>
                        <! . . . .[] . . . . .!>
                        <! . . . . . . . . . .!>
                        <! . . .[] . . . . . .!>
                        <!====================!>
                          \/\/\/\/\/\/\/\/\/\/
```

The best way to reproduce this I found so far is to set `Next.Tetromino` to 0 so I constantly get an `I` block. Then run the game and move the block left and right and rotate a few times. It won't take long for it to go diagonal!

As usual, good stuff :)

**Comment by ARMoir** [comment]
Thanks for opening this!

Yes I have seen the same,  also having trouble determining the root cause on this.

I think it may be due to the Key.Press() being spawned in a separate thread, the Rotate.Check.Lock was supposed to account for this. 

I will have to see if I can find some time tonight to dig a bit more.

**Comment by ARMoir** [comment]
@hamidnazari 
I added the rotate lock to Left and Right movement, which I believe has resolved the issue if you wanted to check it out :)

Key.cs

```
                    case ConsoleKey.LeftArrow:
                    case ConsoleKey.A:
                        if (!Rotate.Check.Lock)
                        {
                            Move.Direction((int)Move.Check.Diretions.Left);
                            Rotate.Check.Lock = true;
                        }
                        break;
```

**Comment by hamidnazari** [comment]
Cool. Seems to have done the job. I couldn't reproduce it. 👍

**Comment by ARMoir** [comment]
@hamidnazari 
Thanks for checking!
